version: "3"
services:
  api:
    build: .
    command: npm run start
    ports:
      - 4000:4000
    environment:
      SEED_DATA: "false"
  database:
    image: "postgres"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
